=begin
#panania

#The API to interface with the db at Panania

OpenAPI spec version: 1.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 1.0.12-1

=end

module RemoteMemberInfo
  VERSION = "1.0.0"
end
