=begin
#remote_member_info

#The API to interface with the db

OpenAPI spec version: 1.0.2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.5

=end

module RemoteMemberInfo
  VERSION = '1.0.0'
end
