=begin
#panania

#The API to interface with the db at Panania

OpenAPI spec version: 1.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 1.0.12-1

=end

require 'spec_helper'
require 'json'

# Unit tests for RemoteMemberInfo::MemberApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MemberApi' do
  before do
    # run before each test
    @instance = RemoteMemberInfo::MemberApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MemberApi' do
    it 'should create an instance of MemberApi' do
      expect(@instance).to be_instance_of(RemoteMemberInfo::MemberApi)
    end
  end

  # unit tests for member_get
  # Gets a member by id
  # 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [User]
  describe 'member_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
