=begin
#panania

#The API to interface with the db at Panania

OpenAPI spec version: 1.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 1.0.12-1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for RemoteMemberInfo::Group
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'Group' do
  before do
    # run before each test
    @instance = RemoteMemberInfo::Group.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Group' do
    it 'should create an instance of Group' do
      expect(@instance).to be_instance_of(RemoteMemberInfo::Group)
    end
  end
  describe 'test attribute "id"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

