=begin
#remote_member_info

#The API to interface with the db

OpenAPI spec version: 1.0.2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.5

=end

# Common files
require 'remote_member_info/api_client'
require 'remote_member_info/api_error'
require 'remote_member_info/version'
require 'remote_member_info/configuration'

# Models
require 'remote_member_info/models/account'
require 'remote_member_info/models/error_model'
require 'remote_member_info/models/group'
require 'remote_member_info/models/user'

# APIs
require 'remote_member_info/api/member_api'

module RemoteMemberInfo
  class << self
    # Customize default settings for the SDK using block.
    #   RemoteMemberInfo.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
